services:
  frontend:
    build: 
      context: .
      dockerfile: ./docker/frontend.dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    environment:
      HASURA_GRAPHQL_ENGINE_URL: ${HASURA_GRAPHQL_ENGINE_URL}
    command: bash -c "yarn install && yarn dev"
  codegen:
    image: node:16
    volumes:
      - ./frontend:/app
    working_dir: /app
    environment:
      HASURA_GRAPHQL_ENGINE_URL: ${HASURA_GRAPHQL_ENGINE_URL}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
    command: bash -c "yarn generate"
    depends_on:
      - frontend
      - graphql-engine
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  tunnel:
    image: node:16
    command: >
      npx localtunnel
      --local-host frontend 
      -p 3000
      -s kanben-web
    depends_on:
      - frontend
  graphql-engine:
    image: hasura/graphql-engine:v2.22.1.cli-migrations-v3
    ports:
    - "8080:8080"
    working_dir: /hasura
    volumes:
    - ./hasura:/hasura
    depends_on:
    - "postgres"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/default
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT: 300
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura/migrations
      HASURA_GRAPHQL_METADATA_DIR: /hasura/metadata
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
volumes:
  db_data:

